class FormLocators:
    GENDER = '//*[contains(text(), "Male")]'
    NAME = '#Name'
    ADDRESS = '#Address'
    Zipcode = '#Zipcode___'
    CITY = '#city'
    PHONE = '#Phonenumbe'
    EMAIL = '#Email_addr'
    BIRTH = '#Date_of_bi'
    SUBMIT = '#btnSubmit'
    RESULT = '#set-viewport'
